USE jugos;
ALTER TABLE tbclientes ADD PRIMARY KEY(DNI);
ALTER TABLE tbclientes ADD COLUMN(FECHA_NACIMIENTO DATE);
INSERT INTO tbclientes (
DNI, NOMBRE, DIRECCION1, DIRECCION2, BARRIO, CIUDAD, ESTADO, CP, EDAD, SEXO, LIMITE_CREDITO, VOLUMEN_COMPRA,
PRIMERA_COMPRA, FECHA_NACIMIENTO) VALUES('456879548','Pedro el Escamoso', 'Calle del Sol, 25', '','Los Laureles',
'CDMX', 'Mexico','65784',55,'M',1000000,2000,0,'1973-05-25');
# campo DATE, el formato es AAAA-MM-DD
SELECT * FROM tbclientes;
UPDATE tbclientes SET FECHA_NACIMIENTO = '1968-05-25' WHERE DNI = '456879548';

# MODIFICAR VENDEDORES
#ALTER TABLE tabla_de_vendedores DROP COLUMN FECHA_ADMISION;
#ALTER TABLE tabla_de_vendedores DROP COLUMN DE_VACACIONES;

ALTER TABLE tabla_de_vendedores ADD PRIMARY KEY(MATRICULA);
ALTER TABLE tabla_de_vendedores ADD COLUMN(FECHA_ADMISION DATE);
ALTER TABLE tabla_de_vendedores ADD COLUMN(DE_VACACIONES VARCHAR(2));
UPDATE tabla_de_vendedores SET FECHA_ADMISION = '2014-08-15',DE_VACACIONES = 'No' WHERE MATRICULA = '00235';
UPDATE tabla_de_vendedores SET FECHA_ADMISION = '2013-09-17',DE_VACACIONES = 'Si',PORCENTAJE_COMISION = 0.08 WHERE MATRICULA = '00236';
INSERT INTO tabla_de_vendedores(MATRICULA,NOMBRE,PORCENTAJE_COMISION,FECHA_ADMISION,DE_VACACIONES) VALUES(
'00237','Roberta Martins',0.11,'2017-03-18','Si');
INSERT INTO tabla_de_vendedores(MATRICULA,NOMBRE,PORCENTAJE_COMISION,FECHA_ADMISION,DE_VACACIONES) VALUES(
'00238','Pericles Alves',0.11,'2016-08-21','No');
SELECT * FROM tabla_de_vendedores;